"""Offline-first building blocks for the governed creative runtime.

The package deliberately contains no provider, credential, network, or canonical
knowledge-store integration.  Those boundaries are checked before later slices
are allowed to add their own deterministic behavior.
"""

from .governance import GovernanceViolation, TaskGovernance, load_task_governance
from .contracts import (
    CreativeArtifact,
    CreativeEvent,
    DirectorBrief,
    GenerationRequest,
    GenerationResult,
    PlayerAction,
    ShotPlan,
    StoryBeat,
    StoryState,
    canonical_json,
)
from .ledger import CreativeLedger, LedgerViolation, create_artifact
from .director import SCENE_CINEMATIC_PROFILES, DirectorCompilation, DirectorQualityMetrics, DirectorSkill, QualityFinding, QualityReport, VerifiedDirectorCompilation, compile_director, compile_verified_director, select_director_skills
from .knowledge import KnowledgeBridgeViolation, KnowledgeCandidate, KnowledgeReviewBridge, VerifiedKnowledgeCandidate, correct_from_verified_timeline
from .local_intake import LocalIntakePolicy, LocalIntakeProjection, LocalIntakeViolation, local_intake_gate_report, validate_local_intake
from .intent import (
    SAFE_INTENT_CONFIDENCE,
    SAFE_INTENT_SCHEMA,
    SafeIntentResolution,
    normalize_safe_intent_text,
    resolve_safe_intent,
    safe_intent_examples,
    safe_intent_projection,
)
from .generation import (
    ExternalGenerationGuard,
    GenerationViolation,
    OfflineGenerationAdapter,
    OfflineGenerationReceipt,
    OfflineGenerationRecord,
    adapter_for,
    offline_generation_receipt_path,
    record_offline_generation,
    verify_offline_generation_record,
)
from .feedback import FeedbackRecord, FeedbackViolation, build_feedback_record, feedback_path, load_feedback, record_feedback
from .provenance import ProvenanceViolation, SourceProvenance, require_reusable_source
from .continuity import (
    GraphBeat,
    GraphTransition,
    StoryGraph,
    TimelineEntry,
    TimelineViolation,
    VerifiedDirectorInput,
    default_story_graph,
    graph_for_initial_state,
    graph_for_ledger,
    harbor_protocol_story_graph,
    night_signal_story_graph,
    replay_timeline,
    three_scene_story_graph,
    timeline_hash,
    verified_director_input,
)
from .coverage import DirectorCoverageEntry, DirectorCoverageReport, RouteCoverageEntry, RouteCoverageReport, RouteCoverageViolation, cover_director_states, coverage_for_scenario, director_coverage_for_scenario, cover_routes, ledger_for_route
from .experience import (
    ExperienceViolation,
    VerifiedExperienceManifest,
    VerifiedScenarioCatalog,
    build_verified_experience,
    build_verified_scenario_catalog,
    verify_verified_experience,
    verify_verified_scenario_catalog,
)
from .experience_library import (
    DEMO_SLOT,
    ExperienceLibraryViolation,
    VerifiedExperienceLibrary,
    artifact_sha256,
    build_synthetic_experience_artifact,
    build_verified_experience_library,
    verify_verified_experience_library,
)
from .director_review import (
    DirectorReviewBoard,
    DirectorReviewViolation,
    build_director_review_board,
    verify_director_review_board,
)
from .presentation import InteractiveFrame, PresentationViolation, build_interactive_frame
from .sequence import SequenceViolation, VerifiedSequencePlan, build_verified_sequence, verify_verified_sequence
from .understanding import (
    DriftAssessment,
    MetricAnchor,
    UnderstandingCard,
    UnderstandingMap,
    UnderstandingViolation,
    assess_anchor,
    bind_verified_timeline,
)
from .session import (
    DEFAULT_SLOT,
    LoadedV2Session,
    MigrationResult,
    SessionViolation,
    V2SourceVerification,
    VerifiedSessionReceipt,
    build_verified_session_receipt,
    legacy_session_path,
    load_v2_session,
    migrate_legacy_session,
    verify_v2_source_binding,
    validate_slot,
    v2_session_path,
)

__all__ = [
    "CreativeArtifact",
    "CreativeEvent",
    "RouteCoverageEntry",
    "RouteCoverageReport",
    "RouteCoverageViolation",
    "CreativeLedger",
    "DirectorCompilation",
    "DirectorCoverageEntry",
    "DirectorCoverageReport",
    "DirectorQualityMetrics",
    "DirectorReviewBoard",
    "DirectorReviewViolation",
    "DirectorBrief",
    "DirectorSkill",
    "DriftAssessment",
    "DEFAULT_SLOT",
    "GenerationRequest",
    "GenerationResult",
    "GenerationViolation",
    "GraphBeat",
    "GraphTransition",
    "InteractiveFrame",
    "ExperienceViolation",
    "ExperienceLibraryViolation",
    "GovernanceViolation",
    "LedgerViolation",
    "LoadedV2Session",
    "KnowledgeBridgeViolation",
    "KnowledgeCandidate",
    "KnowledgeReviewBridge",
    "LocalIntakeProjection",
    "LocalIntakePolicy",
    "LocalIntakeViolation",
    "SafeIntentResolution",
    "MetricAnchor",
    "MigrationResult",
    "ExternalGenerationGuard",
    "FeedbackRecord",
    "FeedbackViolation",
    "OfflineGenerationAdapter",
    "OfflineGenerationReceipt",
    "OfflineGenerationRecord",
    "PlayerAction",
    "PresentationViolation",
    "QualityFinding",
    "QualityReport",
    "ProvenanceViolation",
    "ShotPlan",
    "StoryBeat",
    "StoryGraph",
    "StoryState",
    "VerifiedExperienceManifest",
    "VerifiedExperienceLibrary",
    "VerifiedScenarioCatalog",
    "VerifiedSequencePlan",
    "SourceProvenance",
    "SessionViolation",
    "SequenceViolation",
    "SCENE_CINEMATIC_PROFILES",
    "SAFE_INTENT_CONFIDENCE",
    "SAFE_INTENT_SCHEMA",
    "TaskGovernance",
    "TimelineEntry",
    "TimelineViolation",
    "UnderstandingCard",
    "UnderstandingMap",
    "UnderstandingViolation",
    "VerifiedDirectorInput",
    "VerifiedDirectorCompilation",
    "VerifiedKnowledgeCandidate",
    "V2SourceVerification",
    "VerifiedSessionReceipt",
    "canonical_json",
    "artifact_sha256",
    "normalize_safe_intent_text",
    "adapter_for",
    "assess_anchor",
    "bind_verified_timeline",
    "build_verified_session_receipt",
    "build_interactive_frame",
    "build_feedback_record",
    "build_verified_experience",
    "build_director_review_board",
    "build_synthetic_experience_artifact",
    "build_verified_experience_library",
    "build_verified_scenario_catalog",
    "build_verified_sequence",
    "compile_director",
    "compile_verified_director",
    "cover_routes",
    "cover_director_states",
    "coverage_for_scenario",
    "director_coverage_for_scenario",
    "ledger_for_route",
    "correct_from_verified_timeline",
    "create_artifact",
    "default_story_graph",
    "feedback_path",
    "graph_for_initial_state",
    "graph_for_ledger",
    "harbor_protocol_story_graph",
    "require_reusable_source",
    "select_director_skills",
    "safe_intent_examples",
    "safe_intent_projection",
    "load_task_governance",
    "load_feedback",
    "local_intake_gate_report",
    "legacy_session_path",
    "load_v2_session",
    "migrate_legacy_session",
    "night_signal_story_graph",
    "offline_generation_receipt_path",
    "record_offline_generation",
    "record_feedback",
    "resolve_safe_intent",
    "replay_timeline",
    "timeline_hash",
    "three_scene_story_graph",
    "verified_director_input",
    "verify_verified_experience",
    "verify_director_review_board",
    "verify_verified_experience_library",
    "verify_verified_sequence",
    "verify_verified_scenario_catalog",
    "verify_v2_source_binding",
    "verify_offline_generation_record",
    "validate_slot",
    "validate_local_intake",
    "v2_session_path",
]
