"""Offline-first building blocks for the governed creative runtime.

The package deliberately contains no provider, credential, network, or canonical
knowledge-store integration.  Those boundaries are checked before later slices
are allowed to add their own deterministic behavior.
"""

from .governance import GovernanceViolation, TaskGovernance, load_task_governance
from .contracts import (
    CreativeArtifact,
    CreativeEvent,
    DirectorBrief,
    GenerationRequest,
    GenerationResult,
    PlayerAction,
    ShotPlan,
    StoryBeat,
    StoryState,
    canonical_json,
)
from .ledger import CreativeLedger, LedgerViolation, create_artifact
from .director import DirectorCompilation, DirectorQualityMetrics, DirectorSkill, QualityFinding, QualityReport, VerifiedDirectorCompilation, compile_director, compile_verified_director, select_director_skills
from .knowledge import KnowledgeBridgeViolation, KnowledgeCandidate, KnowledgeReviewBridge, VerifiedKnowledgeCandidate, correct_from_verified_timeline
from .generation import (
    ExternalGenerationGuard,
    GenerationViolation,
    OfflineGenerationAdapter,
    OfflineGenerationReceipt,
    OfflineGenerationRecord,
    adapter_for,
    offline_generation_receipt_path,
    record_offline_generation,
    verify_offline_generation_record,
)
from .feedback import FeedbackRecord, FeedbackViolation, build_feedback_record, feedback_path, load_feedback, record_feedback
from .provenance import ProvenanceViolation, SourceProvenance, require_reusable_source
from .continuity import (
    GraphBeat,
    GraphTransition,
    StoryGraph,
    TimelineEntry,
    TimelineViolation,
    VerifiedDirectorInput,
    default_story_graph,
    graph_for_initial_state,
    graph_for_ledger,
    replay_timeline,
    three_scene_story_graph,
    timeline_hash,
    verified_director_input,
)
from .coverage import RouteCoverageEntry, RouteCoverageReport, RouteCoverageViolation, cover_routes, coverage_for_scenario
from .understanding import (
    DriftAssessment,
    MetricAnchor,
    UnderstandingCard,
    UnderstandingMap,
    UnderstandingViolation,
    assess_anchor,
    bind_verified_timeline,
)
from .session import (
    DEFAULT_SLOT,
    LoadedV2Session,
    MigrationResult,
    SessionViolation,
    V2SourceVerification,
    legacy_session_path,
    load_v2_session,
    migrate_legacy_session,
    verify_v2_source_binding,
    validate_slot,
    v2_session_path,
)

__all__ = [
    "CreativeArtifact",
    "CreativeEvent",
    "RouteCoverageEntry",
    "RouteCoverageReport",
    "RouteCoverageViolation",
    "CreativeLedger",
    "DirectorCompilation",
    "DirectorQualityMetrics",
    "DirectorBrief",
    "DirectorSkill",
    "DriftAssessment",
    "DEFAULT_SLOT",
    "GenerationRequest",
    "GenerationResult",
    "GenerationViolation",
    "GraphBeat",
    "GraphTransition",
    "GovernanceViolation",
    "LedgerViolation",
    "LoadedV2Session",
    "KnowledgeBridgeViolation",
    "KnowledgeCandidate",
    "KnowledgeReviewBridge",
    "MetricAnchor",
    "MigrationResult",
    "ExternalGenerationGuard",
    "FeedbackRecord",
    "FeedbackViolation",
    "OfflineGenerationAdapter",
    "OfflineGenerationReceipt",
    "OfflineGenerationRecord",
    "PlayerAction",
    "QualityFinding",
    "QualityReport",
    "ProvenanceViolation",
    "ShotPlan",
    "StoryBeat",
    "StoryGraph",
    "StoryState",
    "SourceProvenance",
    "SessionViolation",
    "TaskGovernance",
    "TimelineEntry",
    "TimelineViolation",
    "UnderstandingCard",
    "UnderstandingMap",
    "UnderstandingViolation",
    "VerifiedDirectorInput",
    "VerifiedDirectorCompilation",
    "VerifiedKnowledgeCandidate",
    "V2SourceVerification",
    "canonical_json",
    "adapter_for",
    "assess_anchor",
    "bind_verified_timeline",
    "build_feedback_record",
    "compile_director",
    "compile_verified_director",
    "cover_routes",
    "coverage_for_scenario",
    "correct_from_verified_timeline",
    "create_artifact",
    "default_story_graph",
    "feedback_path",
    "graph_for_initial_state",
    "graph_for_ledger",
    "require_reusable_source",
    "select_director_skills",
    "load_task_governance",
    "load_feedback",
    "legacy_session_path",
    "load_v2_session",
    "migrate_legacy_session",
    "offline_generation_receipt_path",
    "record_offline_generation",
    "record_feedback",
    "replay_timeline",
    "timeline_hash",
    "three_scene_story_graph",
    "verified_director_input",
    "verify_v2_source_binding",
    "verify_offline_generation_record",
    "validate_slot",
    "v2_session_path",
]
